name: Node.js CI
# A ogni push e Pull Request sul branch main e develop
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  build-and_test:
    # Use the latest Ubuntu version
    runs-on: ubuntu-latest
    steps:
      # 1. Scarica il codice dal repository
      - name: Checkout codic
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install

      # 3. Run tests with coverage
      - name: Run tests with coverage
        run: npm run test:coverage
